feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: how2sign
# phase: dev
# dataset: phoenix2014
# dataset: phoenix14-si5  #CSL-Daily, phoenix2014-T, phoenix2014, CSL
num_epoch: 100
# load_checkpoints: tmpdev_100.00_epoch0_model.pt
# load_checkpoints: "/home/maveric/Downloads/dev_18.90_PHOENIX14.pt"
work_dir: ./tmp
# work_dir: ./dataset/phoenix2014
# work_dir: ./work_dir/baseline_res18/
batch_size: 1
# random_seed: 0
test_batch_size: 1
num_worker: 1
device: 'cuda'
log_interval: 10000
eval_interval: 5
save_interval: 1
# python in default
evaluate_tool: python
# evaluate_tool: sclite
loss_weights:
  SeqCTC: 1.0
  # VAC
  ConvCTC: 1.0
  Dist: 1.0
#load_weights: ''

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 25, 45]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'dev'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
decode_mode: beam 
# decode_mode: max
model_args:
  # num_classes: 1296 # phoenix
  # num_classes: 1101 #how2sign
  num_classes: 65 # test
  c2d_type: resnet18
  # resnet18, resnet34, resnet50, resnet101, resnet152
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: False
  weight_norm: True
