dataset_root: ./dataset/phoenix2014/phoenix-2014-multisigner
dict_path: ./preprocess/phoenix2014/gloss_dict.npy # dictionary with gloss as key and [index, frequency] as value
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-groundtruth
